---
# Значения по умолчанию для роли users

# Список пользователей для создания
# Каждый элемент может содержать:
#   name: имя пользователя (обязательно)
#   group: имя группы (по умолчанию = name)
#   home: домашняя директория (по умолчанию /home/name)
#   shell: shell пользователя (по умолчанию /bin/bash)
#   create_home: создавать домашнюю директорию (по умолчанию true)
#   update_password: когда обновлять пароль - always (всегда) или on_create (только при создании)
# 
# Пароль для каждого пользователя генерируется автоматически и выводится в консоль
nfs_users:
  - name: nfs_user
    group: nfs_user
    home: /home/nfs_user
    shell: /bin/bash
    create_home: true
    update_password: always