---
# VaultStaticSecret для GitHub token Jenkins
# Синхронизирует секрет из Vault в Kubernetes Secret
#
# Vault путь: secret/jenkins/github
# Kubernetes Secret: jenkins-github-token (namespace: jenkins)
#
# Использование:
#   kubectl apply -f manifests/services/jenkins/jenkins-github-token-vaultstaticsecret.yaml
#
# Проверка:
#   kubectl get secret jenkins-github-token -n jenkins -o yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jenkins-github-token
  namespace: jenkins
  labels:
    app: jenkins
    component: github-token
spec:
  # Ссылка на VaultAuth в namespace vault-secrets-operator
  vaultAuthRef: vault-secrets-operator/default
  
  # Путь к секретному движку KV v2
  mount: secret
  type: kv-v2
  
  # Путь к секрету внутри движка (без префикса mount)
  path: jenkins/github
  
  # Интервал обновления секрета
  refreshAfter: 60s
  
  # Целевой Kubernetes Secret
  destination:
    name: jenkins-github-token
    create: true
