---
# Значения по умолчанию для роли nfs-server

# Пакет NFS сервера (зависит от дистрибутива)
nfs_package: "nfs-kernel-server"

# Сервис NFS
nfs_service: "nfs-kernel-server"

# Путь для экспорта NFS
nfs_export_path: "/exports"

# Опции экспорта (по умолчанию для всех подсетей Kubernetes)
# rw - read-write, sync - синхронная запись, no_subtree_check - не проверять поддерево
nfs_export_options: "*(rw,sync,no_subtree_check,no_root_squash)"
