---
# VaultStaticSecret для Docker Registry credentials Jenkins
# Синхронизирует секрет из Vault в Kubernetes Secret
#
# Vault путь: secret/jenkins/docker-registry
# Kubernetes Secret: jenkins-docker-registry (namespace: jenkins)
#
# Ключи в Vault должны быть:
#   username, password
#
# Использование:
#   kubectl apply -f service/manifests/jenkins/jenkins-docker-registry-vaultstaticsecret.yaml
#
# Проверка:
#   kubectl get secret jenkins-docker-registry -n jenkins -o yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jenkins-docker-registry
  namespace: jenkins
  labels:
    app: jenkins
    component: docker-registry
spec:
  # Ссылка на VaultAuth в namespace vault-secrets-operator
  vaultAuthRef: vault-secrets-operator/default
  
  # Путь к секретному движку KV v2
  mount: secret
  type: kv-v2
  
  # Путь к секрету внутри движка (без префикса mount)
  path: jenkins/docker-registry
  
  # Интервал обновления секрета
  refreshAfter: 60s
  
  # Целевой Kubernetes Secret
  destination:
    name: jenkins-docker-registry
    create: true
